spring:
  config:
    activate:
      on-profile: db-local-window

  datasource:
    url: jdbc:mariadb://localhost:3306/x?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 300000
      pool-name: SpringBootJPAHikariCP
---
spring:
  config:
    activate:
      on-profile: db-beta-linux

  datasource:
    url: jdbc:mariadb://192.168.182.79:3306/x?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 300000
      pool-name: SpringBootJPAHikariCP
